#!/system/bin/sh 
#
# Parallax Charger Max

#Parallax DIR
Parallax_DIR=/data/media/0/Parallax
cm=`getprop persist.charger.profile`;

rvalue() {
if [ -f $Parallax_DIR/charger ]; then
	rm -f $Parallax_DIR/charger
fi
}

chmod 666 /sys/class/power_supply/battery/constant_charge_current_max

if [ "$cm" = "1" ]; then
	echo "3000000" > /sys/class/power_supply/battery/constant_charge_current_max
	rvalue()
	echo "1" >> $Parallax_DIR/charger
else
	if [ "$cm" = "2" ]; then
		echo "3300000" > /sys/class/power_supply/battery/constant_charge_current_max
		rvalue()
		echo "2" >> $Parallax_DIR/charger
	else
		if [ "$cm" = "3" ]; then
			echo "1200000" > /sys/class/power_supply/battery/constant_charge_current_max
			if [ ! -f $Parallax_DIR/charger ]; then
				echo "0" >> $Parallax_DIR/charger
			fi
		else
			if [ "$cm" = "4" ]; then
				echo "1800000" > /sys/class/power_supply/battery/constant_charge_current_max
				rvalue()
				echo "4" >> $Parallax_DIR/charger
			else
				echo "2800000" > /sys/class/power_supply/battery/constant_charge_current_max
				rvalue()
				echo "0" >> $Parallax_DIR/charger
			fi
		fi
	fi
fi

chmod 444 /sys/class/power_supply/battery/constant_charge_current_max
# echo "Y" > /sys/module/qpnp_fg_gen3/parameters/charge_boost_enabled

#vcm=`cat /sys/class/power_supply/battery/constant_charge_current_max`;

#echo "Parallax Kernel" >> $Parallax_DIR/charger
#echo "--------------------------" >> $Parallax_DIR/charger
#echo "" >> $Parallax_DIR/charger
#echo "Charger Setted : $vcm" >> $Parallax_DIR/charger
#echo "" >> $Parallax_DIR/charger
#echo "--------------------------" >> $Parallax_DIR/charger
