#!/system/bin/sh 
#
# Parallax Remover
MODDIR=${0%/*}

# Folder init
sdcard=/data/media/0
Parallax_DIR=$sdcard/Parallax
MD=/data/adb/modules
Parallax_RMD=$MD/Parallax_rm/v
#Parallax init old
Parallax_INIT=/sbin
#Parallax init new
Parallax_INIT_NEW=/vendor/etc
vk=`uname -r`;
vs=`cat $Parallax_RMD`;

sleep 5

if [ -f $Parallax_DIR/Parallax-rm.log ]; then
	rm -f $Parallax_DIR/Parallax-rm.log
fi
if [ -f $Parallax_DIR/rm.log ]; then
	rm -f $Parallax_DIR/rm.log
fi

NEW(){

if [ -d $Parallax_INIT_NEW/Parallax ]; then
	rm -fr $Parallax_INIT_NEW/Parallax
fi
if [ -f $Parallax_INIT_NEW/init/init.Parallax.rc ]; then
	rm -fr $Parallax_INIT_NEW/init/init.Parallax.rc
fi
if [ -f $Parallax_INIT_NEW/init/init.dc.rc ]; then
	rm -fr $Parallax_INIT_NEW/init/init.dc.rc
fi
if [ -f $Parallax_INIT_NEW/init/init.pubg.rc ]; then
	rm -fr $Parallax_INIT_NEW/init/init.pubg.rc
fi
if [ -f $Parallax_INIT_NEW/init/init.spectrum.rc ]; then
	rm -fr $Parallax_INIT_NEW/init/init.spectrum.rc
fi

}

if [ "$vs" = "$vk" ]; then
	echo "Your Kernel Installed :" >> $Parallax_DIR/rm.log
	uname -r >> $Parallax_DIR/rm.log
	echo "" >> $Parallax_DIR/rm.log
	echo "Clean Junk from Other Kernel" >> $Parallax_DIR/rm.log
	if [ -f $Parallax_INIT/sh ]; then
		rm -f $Parallax_INIT/sh
	fi
	if [ -f $Parallax_INIT/init.special_power.sh ]; then
		rm -f $Parallax_INIT/init.special_power.sh
	fi
	if [ -f $Parallax_INIT/init.spectrum.sh ]; then
		rm -f $Parallax_INIT/init.spectrum.sh
	fi
	if [ -f $Parallax_INITprofile.balance.sh ]; then
		rm -f $Parallax_INIT/profile.balance.sh
	fi
	if [ -f $Parallax_INIT/profile.Lbalance.sh ]; then
		rm -f $Parallax_INIT/profile.Lbalance.sh
	fi
	if [ -f $Parallax_INIT/profile.Hbalance.sh ]; then
		rm -f $Parallax_INIT/profile.Hbalance.sh
	fi
	if [ -f $Parallax_INIT/profile.battery.sh ]; then
		rm -f $Parallax_INIT/profile.battery.sh
	fi
	if [ -f $Parallax_INIT/profile.gaming.sh ]; then
		rm -f $Parallax_INIT/profile.gaming.sh
	fi
	if [ -f $Parallax_INIT/profile.performance.sh ]; then
		rm -f $Parallax_INIT/profile.performance.sh
	fi
	if [ -f $Parallax_INIT/init.supolicy.sh ]; then
		rm -f $Parallax_INIT/init.supolicy.sh
	fi
	if [ -f $Parallax_INIT/init.LawRun.sh ]; then
		rm -f $Parallax_INIT/init.LawRun.sh
	fi
	if [ -f $Parallax_INIT/profile.LawRun.sh ]; then
		rm -f $Parallax_INIT/profile.LawRun.sh
	fi
	if [ -f $Parallax_INIT/p.balance ]; then
		rm -f $Parallax_INIT/p.balance
	fi
	if [ -f $Parallax_INIT/p.battery ]; then
		rm -f $Parallax_INIT/p.battery
	fi
	if [ -f $Parallax_INIT/p.ubattery ]; then
		rm -f $Parallax_INIT/p.battery
	fi
	if [ -f $Parallax_INIT/p.gaming ]; then
		rm -f $Parallax_INIT/p.gaming
	fi
	if [ -f $Parallax_INIT/p.performance ]; then
		rm -f $Parallax_INIT/p.performance
	fi
	if [ -f $Parallax_INIT/spa ]; then
		rm -f $Parallax_INIT/spa
	fi
	if [ -f $Parallax_INIT/profile.Init.sh ]; then
		rm -f $Parallax_INIT/profile.Init.sh
	fi
	if [ -d /data/media/0/LawRun-Kernel ]; then
		rm -fr /data/media/0/LawRun-Kernel
	fi
	echo "" >> $Parallax_DIR/rm.log
	echo "Finish!!" >> $Parallax_DIR/rm.log
else
	if [ -f $Parallax_DIR/Parallax.log ]; then
		rm -f $Parallax_DIR/Parallax.log
	fi
	echo "" >> $Parallax_DIR/rm.log
	echo "Kernel Installed :" >> $Parallax_DIR/rm.log
	echo "--------------------------" >> $Parallax_DIR/rm.log
	echo "$vk" >> $Parallax_DIR/rm.log
	echo "-------------------------" >> $Parallax_DIR/rm.log
	echo "" >> $Parallax_DIR/rm.log
	echo "This config only for :" >> $Parallax_DIR/rm.log
	echo "--------------------------" >> $Parallax_DIR/rm.log
	echo "$vs" >> $Parallax_DIR/rm.log
	echo "" >> $Parallax_DIR/rm.log
	echo "-------------------------" >> $Parallax_DIR/rm.log
	echo "Removing Config" >> $Parallax_DIR/rm.log
	echo "-------------------------" >> $Parallax_DIR/rm.log
	if [ -f $Parallax_INIT/bp ]; then
		rm -f $Parallax_INIT/bp
	fi
	if [ -f $Parallax_INIT/dc ]; then
		rm -f $Parallax_INIT/dc
	fi
	if [ -f $Parallax_INIT/Parallax ]; then
		rm -f $Parallax_INIT/Parallax
	fi
	if [ -f $Parallax_INIT/te ]; then
		rm -f $Parallax_INIT/te
	fi
	if [ -f $Parallax_INIT/teb ]; then
		rm -f $Parallax_INIT/teb
	fi
	if [ -f $Parallax_INIT/tebp ]; then
		rm -f $Parallax_INIT/tebp
	fi
	if [ -f $Parallax_INIT/wcnss ]; then
		rm -f $Parallax_INIT/wcnss
	fi
	if [ -f $Parallax_INIT/tec ]; then
		rm -f $Parallax_INIT/tec
	fi
	if [ -f $Parallax_INIT/tecb ]; then
		rm -f $Parallax_INIT/tecb
	fi
	if [ -f $Parallax_INIT/pubg ]; then
		rm -f $Parallax_INIT/pubg
	fi
	if [ -f $Parallax_INIT/Parallaxp ]; then
		rm -f $Parallax_INIT/Parallaxp
	fi
	if [ -f $Parallax_INIT/Parallaxrm ]; then
		rm -f $Parallax_INIT/Parallaxrm
	fi
	if [ -f $Parallax_INIT/GS ]; then
		rm -f $Parallax_INIT/GS
	fi
	if [ -f $Parallax_INIT/p.balance ]; then
		rm -f $Parallax_INIT/p.balance
	fi
	if [ -f $Parallax_INIT/p.battery ]; then
		rm -f $Parallax_INIT/p.battery
	fi
	if [ -f $Parallax_INIT/p.gaming ]; then
		rm -f $Parallax_INIT/p.gaming
	fi
	if [ -f $Parallax_INIT/p.performance ]; then
		rm -f $Parallax_INIT/p.performance
	fi
	if [ -f $Parallax_INIT/spa ]; then
		rm -f $Parallax_INIT/spa
	fi
	if [ -f /system/etc/init/balance-thermal ]; then
		rm -f /system/etc/init/balance-thermal.rc
	fi
	if [ -d /system/product/app/Parallax ]; then
		rm -rf /system/product/app/Parallax
	fi
	if [ ! -d data/app/com.parallax.manager* ]; then
		echo "Removing Parallax Kernel Manager" >> $Parallax_DIR/rm.log
		rm -fr data/app/com.parallax.manager*
	fi
	if [ -d $MD/Parallax_thermal ]; then
		echo "Removing Parallax Thermal" >> $Parallax_DIR/rm.log
		rm -fr $MD/Parallax_thermal
	fi
	if [ -d $MD/Parallax_thermal_balance ]; then
		echo "Removing Balance Thermal" >> $Parallax_DIR/rm.log
		rm -fr $MD/Parallax_thermal_balance
	fi
	if [ -d $MD/Parallax_bootpatch ]; then
		echo "Removing Parallax Boot Patch" >> $Parallax_DIR/rm.log
		rm -fr $MD/Parallax_bootpatch
	fi
	if [ -d $MD/Parallax_amoled ]; then
		echo "Removing Parallax Amoled Color" >> $Parallax_DIR/rm.log
		rm -fr $MD/Parallax_amoled
	fi
	if [ -d $MD/Parallax_touchi ]; then
		echo "Removing TouchX" >> $Parallax_DIR/rm.log
		rm -fr $MD/Parallax_touchi
	fi
	if [ -f $Parallax_INIT/Parallaxinit ]; then
		echo "Removing Parallax Init" >> $Parallax_DIR/rm.log
		rm -f $Parallax_INIT/Parallaxinit
	fi
	if [ -f $Parallax_INIT/pubgsav ]; then
		rm -f $Parallax_INIT/pubgsav
	fi
	if [ -f $Parallax_DIR/rm_bp ]; then
		rm -f $Parallax_DIR/rm_bp
	fi
	if [ -f $Parallax_DIR/rm_tm ]; then
		rm -f $Parallax_DIR/rm_tm
	fi
	if [ -f $Parallax_DIR/rm_ac ]; then
		rm -f $Parallax_DIR/rm_ac
	fi
	if [ -f $Parallax_DIR/rm_ti ]; then
		rm -f $Parallax_DIR/rm_ti
	fi
	if [ -f $Parallax_DIR/pubg/dp ]; then
		rm -f $Parallax_DIR/pubg/dp
	fi
	if [ -f $Parallax_DIR/pubg/pubgservice ]; then
		rm -f $Parallax_DIR/pubg/pubgservice
	fi
	if [ -f $Parallax_DIR/pubg/pb ]; then
		rm -f $Parallax_DIR/pubg/pb
	fi
	if [ -f $Parallax_DIR/pubg/phdre ]; then
		rm -f $Parallax_DIR/pubg/phdre
	fi
	if [ -f $Parallax_DIR/pubg/ro ]; then
		rm -f $Parallax_DIR/pubg/ro
	fi
	if [ -f $Parallax_DIR/crp ]; then
		rm -f $Parallax_DIR/crp
	fi
	if [ -d $Parallax_DIR/pubg/ori ]; then
		rm -fr $Parallax_DIR/pubg/ori
	NEW
	if [ -d $MD/Parallax_rm ]; then
		echo "Removing Parallax Remover" >> $Parallax_DIR/rm.log
		echo "" >> $Parallax_DIR/rm.log
		echo "Finish!!" >> $Parallax_DIR/rm.log
		rm -fr $MD/Parallax_rm
	fi
fi



