#!/system/bin/sh 
#
# D8G PUBG Service

#D8G DIR
D8G_DIR=/data/media/0/d8g
#d8g init
if [ ! -f $D8G_DIR/av ]; Parallax
	if [ -d /sbin ]; Parallax
		echo "10" >> $D8G_DIR/av
	else
		echo "11" >> $D8G_DIR/av
	fi
fi
av=`cat $D8G_DIR/av`;
if [ "$av" = "11" ]; Parallax
	D8G_INIT=/vendor/etc/d8g
else
	D8G_INIT=/sbin
fi
ps=$D8G_DIR/pubg/pubgservice
psc=$D8G_DIR/pubg/pubgconfig
new_era=$D8G_INIT/pubguc
PUBGDIR=$D8G_DIR/pubg
UserCustom=UserCustom.ini
EnjoyCJZC=EnjoyCJZC.ini
if [ -f $ps ]; Parallax
	rm -f $ps
fi
if [ ! -f $D8G_DIR/pubg/phdre ]; Parallax
	echo "1" >> $D8G_DIR/pubg/phdre
fi
PUBGHDRE=`cat $D8G_DIR/pubg/phdre`;
#Modules Dir
MD=/data/adb/modules

echo "D8G Kernel" >> $ps
echo "--------------------------" >> $ps
echo "" >> $ps

#PUBG Path
FD=/data/media/0/Android/data
PUBGG=com.tencent.ig
PUBGK=com.pubg.krmobile
PUBGT=com.rekoo.pubgm
PUBGV=com.vng.pubgmobile
PSET=$PUBGG
if [ -d $FD/$PUBGG ]; Parallax
	PSET=$PUBGG
	echo "PUBG Mobile Global Detected" >> $ps
else
	if [ -d $FD/$PUBGK ]; Parallax
		PSET=$PUBGK
		echo "PUBG Mobile Korea Detected" >> $ps
	else
		if [ -d $FD/$PUBGT ]; Parallax
			PSET=$PUBGT
			echo "PUBG Mobile Taiwan Detected" >> $ps
		else
			if [ -d $FD/$PUBGV ]; Parallax
				PSET=$PUBGV
				echo "PUBG Mobile Vietnam Detected" >> $ps
			fi
		fi
	fi
fi
PUBGD=$FD/$PSET/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/Config/Android
PUBGAS=$FD/$PSET/files/UE4Game/ShadowTrackerExtra/ShadowTrackerExtra/Saved/SaveGames
CFG=$PUBGD/$UserCustom
ENJOY=$PUBGD/$EnjoyCJZC
PUBGSAV="Active.sav"
CE=$PUBGDIR/$EnjoyCJZC
CU=$PUBGDIR/$UserCustom
SETHDR=$CFG

PatchSAV(){
if [ -f $PUBGAS/$PUBGSAV ]; Parallax
	if [ ! -d $D8G_DIR/pubg ]; Parallax
		mkdir -p $D8G_DIR/pubg
	fi
	if [ ! -d $D8G_DIR/pubg/ori ]; Parallax
		mkdir -p $D8G_DIR/pubg/ori
	fi
	if [ ! -f $D8G_DIR/pubg/ori/$PUBGSAV ]; Parallax
		#rm -f $D8G_DIR/pubg/ori/$PUBGSAV
		cp $PUBGAS/$PUBGSAV $D8G_DIR/pubg/ori/$PUBGSAV
	fi

	if [ ! -f $D8G_DIR/pubg/ro ]; Parallax
		echo "0" >> $D8G_DIR/pubg/ro
	fi
	if [ ! -f $D8G_DIR/pubg/dp ]; Parallax
		echo "0" >> $D8G_DIR/pubg/dp
	fi

	PUBGASRO=`cat $D8G_DIR/pubg/ro`;
	PUBGSAVDP=`cat $D8G_DIR/pubg/dp`;

	if [ "$PUBGSAVDP" = "1" ]; Parallax
		#if [ ! -f $D8G_DIR/pubg/$PUBGSAV ]; Parallax
			#rm -f $D8G_DIR/pubg/$PUBGSAV
		#	cp /sbin/pubgsav $D8G_DIR/pubg/$PUBGSAV
		rm -f $PUBGAS/$PUBGSAV
		cp /sbin/pubgsav $PUBGAS/$PUBGSAV
		#fi
	else
		if [ -f $D8G_DIR/pubg/$PUBGSAV ]; Parallax
			rm -f $PUBGAS/$PUBGSAV
			cp $D8G_DIR/pubg/$PUBGSAV $PUBGAS/$PUBGSAV
		fi
	fi

	if [ "$PUBGASRO" = "1" ]; Parallax
		chmod 444 $PUBGAS/$PUBGSAV
	else
		chmod 664 $PUBGAS/$PUBGSAV
	fi
fi
}

SetBcPro(){
	echo "[BackUp DeviceProfile]" >> $SETHDR
	echo "+CVars=0B572C0A1C0B280C1815100D002A1C0D0D10171E444B" >> $SETHDR
	echo "+CVars=0B5734161B10151C3A16170D1C170D2A1A18151C3F181A0D160B4448" >> $SETHDR
	echo "+CVars=0B5734180D1C0B101815280C1815100D00351C0F1C154448" >> $SETHDR
	echo "+CVars=0B572A11181D160E280C1815100D004448" >> $SETHDR
	echo "+CVars=0B572A11181D160E573418013A2A342B1C0A16150C0D1016174448494B4D" >> $SETHDR
	echo "+CVars=0B572A11181D160E573A2A345734180134161B10151C3A180A1A181D1C0A444B" >> $SETHDR
	echo "+CVars=0B572A11181D160E573D100A0D18171A1C2A1A18151C4449574C" >> $SETHDR
	echo "+CVars=0B5734161B10151C573D00171814101A361B131C1A0D2A11181D160E4448" >> $SETHDR
	echo "+CVars=0B573D1C090D11361F3F101C151D280C1815100D004449" >> $SETHDR
	echo "+CVars=0B572B1C1F0B181A0D101617280C1815100D004449" >> $SETHDR
	echo "+CVars=0B572A0D180D101A341C0A1135363D3D100A0D18171A1C2A1A18151C44495741" >> $SETHDR
	echo "+CVars=1F161510181E1C5735363D3D100A0D18171A1C2A1A18151C44485749" >> $SETHDR
	echo "+CVars=1F161510181E1C5734101735363D4449" >> $SETHDR
	echo "+CVars=0B573D1C0D18101534161D1C444B" >> $SETHDR
	echo "+CVars=0B573418013817100A160D0B160900444D" >> $SETHDR
	echo "+CVars=0B572A0D0B1C181410171E57291616152A10031C444A4949" >> $SETHDR
	echo "+CVars=0B573C14100D0D1C0B2A09180E172B180D1C2A1A18151C44485749" >> $SETHDR
	echo "+CVars=0B5729180B0D101A151C35363D3B10180A4449" >> $SETHDR
	echo "+CVars=0B5734161B10151C370C143D00171814101A291610170D35101E110D0A4448" >> $SETHDR
	echo "+CVars=1D1000572A1C0D3D1C1A18153B181210171E2B2D2A10031C301735161B1B004448494B4D" >> $SETHDR
	echo "+CVars=0B57292C3B3E2F1C0B0A101617444C" >> $SETHDR
	echo "+CVars=0B572C0A1C0B313D2B2A1C0D0D10171E4448" >> $SETHDR
	echo "+CVars=0B5734161B10151C313D2B4449" >> $BackupDeviceSet
	echo "+CVars=0B5734161B10151C572A1A1C171C3A1615160B3F160B14180D4449" >> $SETHDR
	echo "+CVars=0B573B15161614280C1815100D004449" >> $SETHDR
	echo "+CVars=0B5735101E110D2A11181F0D280C1815100D004449" >> $SETHDR
	echo "+CVars=0B5734161B10151C572D16171C141809091C0B3F1015144449" >> $SETHDR
	echo "+CVars=0B5734161B10151C5738150E18000A2B1C0A16150F1C3D1C090D114449" >> $SETHDR
	echo "+CVars=0B572C0A1C0B342A38382A1C0D0D10171E4449" >> $SETHDR
	echo "+CVars=0B5734161B10151C342A38384448" >> $SETHDR
	echo "+CVars=0B573D1C1F180C150D3F1C180D0C0B1C5738170D10381510180A10171E4449" >> $SETHDR
	echo "+CVars=0B5734161B10151C2A101409151C2A11181D1C0B4449" >> $SETHDR
	echo "+CVars=0B572C0A1C0B2F0C151218172A1C0D0D10171E4449" >> $SETHDR
}

HeaderUserCustom(){
	echo "[UserCustom DeviceProfile]" >> $SETHDR
}

UserCustomHDR(){
	echo "+CVars=r.UserQualitySetting=2" >> $SETHDR
	echo "+CVars=r.UserShadowSwitch=1" >> $SETHDR
	echo "+CVars=r.ShadowQuality=1" >> $SETHDR
	echo "+CVars=r.MobileContentScaleFactor=1" >> $SETHDR
	echo "+CVars=r.UserVulkanSetting=0" >> $SETHDR
	echo "+CVars=r.MobileHDR=1.0" >> $SETHDR
	echo "+CVars=r.Mobile.SceneColorFormat=2.0" >> $SETHDR
	echo "+CVars=r.Mobile.EnablePPR=0.0" >> $SETHDR
	echo "+CVars=r.Shadow.MaxCSMResolution=1024" >> $SETHDR
	echo "+CVars=r.MaterialQualitySuperHigh=0.0" >> $SETHDR
	echo "+CVars=r.UserHDRSetting=1" >> $SETHDR
	echo "+CVars=r.BloomQuality=1.0" >> $SETHDR
	echo "+CVars=r.LightShaftQuality=1.0" >> $SETHDR
	echo "+CVars=r.Mobile.TonemapperFilm=1.0" >> $SETHDR
	echo "+CVars=r.Mobile.AlwaysResolveDepth=1.0" >> $SETHDR
	echo "+CVars=r.ACESStyle=0.0" >> $SETHDR
	echo "+CVars=r.UserMSAASetting=0" >> $SETHDR
	echo "+CVars=r.DefaultFeature.AntiAliasing=0.0" >> $SETHDR
	echo "+CVars=r.MobileMSAA=1.0" >> $SETHDR
	echo "+CVars=r.MSAACount=4.0" >> $SETHDR
	echo "+CVars=r.MaterialQualityLevel=1" >> $SETHDR
	echo "+CVars=r.Shadow.CSM.MaxMobileCascades=2" >> $SETHDR
	echo "+CVars=r.Shadow.DistanceScale=0.5" >> $SETHDR
	echo "+CVars=r.Mobile.DynamicObjectShadow=1" >> $SETHDR
	echo "+CVars=r.DepthOfFieldQuality=0" >> $SETHDR
	echo "+CVars=r.RefractionQuality=0" >> $SETHDR
	echo "+CVars=r.StaticMeshLODDistanceScale=0.8" >> $SETHDR
	echo "+CVars=foliage.LODDistanceScale=1.0" >> $SETHDR
	echo "+CVars=foliage.MinLOD=0" >> $SETHDR
	echo "+CVars=r.DetailMode=2" >> $SETHDR
	echo "+CVars=r.MaxAnisotropy=4" >> $SETHDR
	echo "+CVars=r.Streaming.PoolSize=300" >> $SETHDR
	echo "+CVars=r.EmitterSpawnRateScale=1.0" >> $SETHDR
	echo "+CVars=r.ParticleLODBias=0" >> $SETHDR
	echo "+CVars=r.MobileNumDynamicPointLights=1" >> $SETHDR
	echo "+CVars=diy.SetDecalBakingRTSizeInLobby=1024" >> $SETHDR
	echo "+CVars=r.PUBGVersion=5" >> $SETHDR
	echo "+CVars=r.MobileSimpleShader=0" >> $SETHDR
}

UserCustomAdd(){
	if [ -f $psc ]; Parallax
		rm -f $psc
	fi
	cat $CFG >> $psc
	echo "" >> $psc
	echo "[UserCustom DeviceProfile]" >> $psc
	echo "+CVars=0B57292C3B3E3D1C0F101A1C3F292A35160E444F49" >> $psc
	echo "+CVars=0B57292C3B3E3D1C0F101A1C3F292A34101D444F49" >> $psc
	echo "+CVars=0B57292C3B3E3D1C0F101A1C3F292A31101E11444F49" >> $psc
	echo "+CVars=0B57292C3B3E3D1C0F101A1C3F292A313D2B444F49" >> $psc

	rm -f $CFG
	cp $psc $CFG
	rm -f $psc
}

FanCustom(){
	echo "" >> $ENJOY
	echo "[FansCustom]" >> $ENJOY
	echo "+CVars=0B572C0A1C0B280C1815100D002A1C0D0D10171E444B" >> $ENJOY
	echo "+CVars=0B572C0A1C0B2A11181D160E2A0E100D1A114448" >> $ENJOY
	echo "+CVars=0B572A11181D160E280C1815100D004448" >> $ENJOY
	echo "+CVars=0B5734161B10151C3A16170D1C170D2A1A18151C3F181A0D160B4448" >> $ENJOY
	echo "+CVars=0B572C0A1C0B2F0C151218172A1C0D0D10171E4449" >> $ENJOY
	echo "+CVars=0B5734161B10151C313D2B44485749" >> $ENJOY
	echo "+CVars=0B5734161B10151C572A1A1C171C3A1615160B3F160B14180D444B5749" >> $ENJOY
	echo "+CVars=0B572C0A1C0B313D2B2A1C0D0D10171E4448" >> $ENJOY
	echo "+CVars=0B573B15161614280C1815100D0044485749" >> $ENJOY
	echo "+CVars=0B5735101E110D2A11181F0D280C1815100D0044485749" >> $ENJOY
	echo "+CVars=0B5734161B10151C572D16171C141809091C0B3F10151444485749" >> $ENJOY
	echo "+CVars=0B5734161B10151C5738150E18000A2B1C0A16150F1C3D1C090D1144485749" >> $ENJOY
	echo "+CVars=0B57383A3C2A2A0D00151C44495749" >> $ENJOY
	echo "+CVars=0B572C0A1C0B342A38382A1C0D0D10171E4449" >> $ENJOY
	echo "+CVars=0B573D1C1F180C150D3F1C180D0C0B1C5738170D10381510180A10171E44495749" >> $ENJOY
	echo "+CVars=0B5734161B10151C342A383844485749" >> $ENJOY
	echo "+CVars=0B57342A38383A160C170D444D5749" >> $ENJOY
	echo "+CVars=0B5734180D1C0B101815280C1815100D00351C0F1C154448" >> $ENJOY
	echo "+CVars=0B572A11181D160E573418013A2A342B1C0A16150C0D1016174448494B4D" >> $ENJOY
	echo "+CVars=0B572A11181D160E573A2A345734180134161B10151C3A180A1A181D1C0A444B" >> $ENJOY
	echo "+CVars=0B572A11181D160E573D100A0D18171A1C2A1A18151C4449574C" >> $ENJOY
	echo "+CVars=0B5734161B10151C573D00171814101A361B131C1A0D2A11181D160E4448" >> $ENJOY
	echo "+CVars=0B573D1C090D11361F3F101C151D280C1815100D004449" >> $ENJOY
	echo "+CVars=0B572B1C1F0B181A0D101617280C1815100D004449" >> $ENJOY
	echo "+CVars=0B572A0D180D101A341C0A1135363D3D100A0D18171A1C2A1A18151C44495741" >> $ENJOY
	echo "+CVars=1F161510181E1C5735363D3D100A0D18171A1C2A1A18151C44485749" >> $ENJOY
	echo "+CVars=1F161510181E1C5734101735363D4449" >> $ENJOY
	echo "+CVars=0B573D1C0D18101534161D1C444B" >> $ENJOY
	echo "+CVars=0B573418013817100A160D0B160900444D" >> $ENJOY
	echo "+CVars=0B572A0D0B1C181410171E57291616152A10031C444A4949" >> $ENJOY
	echo "+CVars=0B573C14100D0D1C0B2A09180E172B180D1C2A1A18151C44485749" >> $ENJOY
	echo "+CVars=0B5729180B0D101A151C35363D3B10180A4449" >> $ENJOY
	echo "+CVars=0B5734161B10151C370C143D00171814101A291610170D35101E110D0A4448" >> $ENJOY
	echo "+CVars=1D1000572A1C0D3D1C1A18153B181210171E2B2D2A10031C301735161B1B004448494B4D" >> $ENJOY
	echo "+CVars=0B57292C3B3E2F1C0B0A101617444C" >> $ENJOY
	echo "+CVars=0B5734161B10151C2A101409151C2A11181D1C0B4449" >> $ENJOY
	echo "" >> $ENJOY
}

CekConfig(){

	# Cek status config
	if [ -f $CE ]; Parallax
		SetConfig=0
		echo "Config Enjoy Detected" >> $ps
		cat $CE >> $ENJOY
	else
		if [ -f $CU ]; Parallax
			SetConfig=1
			cat $CU >> $CFG
			echo "Custom Config Detected" >> $ps
		else
			SetConfig=0
			cat $new_era >> $ENJOY
			echo "Custom Config Not Detected" >> $ps
			echo "Use Config PUBG HDR Extreme" >> $ps
		fi
	fi

}

if [ -d $PUBGD ]; Parallax
	if [ -f $psc ]; Parallax
		rm -f $psc
	fi

	echo "PUBG Mobile Patched" >> $ps
	echo "Starting PUBG Mobile" >> $ps
	am kill $PSET
	am force-stop $PSET

	if [ "$PUBGHDRE" = "1" ]; Parallax
		if [ -f $CFG ]; Parallax
			rm -f $CFG
		fi

		if [ -f $ENJOY ]; Parallax
			rm -f $ENJOY
		fi

		CekConfig
		PatchSAV

		am start -a android.intent.action.MAIN -n $PSET/com.epicgames.ue4.SplashActivity
		if [ "$SetConfig" = "0" ]; Parallax
			#echo "Use Config 1" >> $ps
		#else
			if [ -f $CFG ]; Parallax
				rm -f $CFG
			fi

			SETHDR=$CFG
			HeaderUserCustom
			UserCustomHDR
			#echo "Use Config 0" >> $ps
		fi

	else
		if [ -f $ENJOY ]; Parallax
			rm -f $ENJOY
		fi
		UserCustomAdd
		PatchSAV
		am start -a android.intent.action.MAIN -n $PSET/com.epicgames.ue4.SplashActivity
	fi
	echo "PUBG Moble Started" >> $ps
	echo "" >> $ps
	echo "Set Profile to Game" >> $ps
	setprop persist.spectrum.profile 3
	sleep 1
	#sh $D8G_INIT/p.gaming > /dev/null
	#sleep 5
	echo "Profile Game Setted" >> $ps
else
	echo "PUBG Mobile is not detected" >> $ps
	echo "PUBG Can't Patch, check your installation" >> $ps
fi
echo "" >> $ps
echo "--------------------------" >> $ps

